const I18N={
ru:{
nav:['01 ДЕТИ','02 ПЕЧЬ','03 ПОЖАР','04 ЭЛЕКТРИКА','05 ПРОВЕРКА','BOT','APP'],
heroEy:'ПАМЯТКА · СЕМЬЯ · БЕЗОПАСНОСТЬ',heroTitle:'ДОМ,<br><span>ГДЕ НЕ</span><br>СТРАШНО.',heroP:'Короткая интерактивная памятка: проверьте окна, печь, электрику и подготовьте семью к чрезвычайной ситуации.',check:'ПРОВЕРИТЬ ДОМ',quick:'БЫСТРО К ГЛАВНОМУ',fire:'ПОЖАРНАЯ<br>СЛУЖБА',unified:'ЕДИНЫЙ<br>НОМЕР',brand:'ДЕПАРТАМЕНТ ПО ЧС СКО ПРЕДУПРЕЖДАЕТ',
quickSmall:'С ЧЕГО НАЧАТЬ',quickTitle:'4 вещи, которые<br><em>нужно проверить</em> сегодня.',quickCards:[['ОКНА','Блокираторы · мебель'],['ПЕЧЬ','Дымоход · трещины · тяга'],['ЭЛЕКТРИКА','Провода · розетки · приборы'],['ИЗВЕЩАТЕЛЬ','Работа · батарея · тест']],
sitSmall:'ВЫБЕРИТЕ СИТУАЦИЮ',sitTitle:'ЧТО ВАС<br><em>БЕСПОКОИТ?</em>',sitP:'Не листайте всю памятку. Выберите ситуацию — сайт сразу перенесёт вас к нужным действиям.',sitCards:['Ребёнок<br>у окна','Печь<br>и отопление','Начался<br>пожар','Электрика<br>и приборы','Дымовой<br>извещатель'],
downloadSmall:'МОЖНО СОХРАНИТЬ',downloadTitle:'Скачайте памятку на русском языке',downloadLabels:['ОКНА ↓','ПЕЧЬ ↓','ПОЖАР ↓','ЭЛЕКТРИКА ↓','ИЗВЕЩАТЕЛЬ ↓'],
manifestoSmall:'САМОЕ ВАЖНОЕ',manifestoTitle:'Опасность не<br>предупреждает.',manifestoP:'Поэтому проверять дом лучше <strong>до</strong> того, как что-то произойдёт. Здесь — конкретные действия без лишнего текста.',
kidsSmall:'01 / ДЕТИ',kidsBtn:'СКАЧАТЬ ПАМЯТКУ PDF ↓',kidsTitle:'Маленький<br><em>шаг.</em> Большая защита.',kidsCaption:'ОКНО ≠ МЕСТО ДЛЯ ИГРЫ',kidsRulesTitle:'ПЯТЬ ПРИВЫЧЕК',kidsRules:['Не оставляйте ребёнка без присмотра.','Не оставляйте окна открытыми настежь.','Установите оконные блокираторы.','Не ставьте мебель возле окна.','Объясните ребёнку опасность открытого окна.'],
stoveSmall:'02 / ОТОПЛЕНИЕ',stoveBtn:'СКАЧАТЬ ПАМЯТКУ PDF ↓',stoveTitle:'ПЕРЕД ХОЛОДАМИ<br><em>ПРОВЕРЬ ПЕЧЬ.</em>',stoveOverlay:'ТЕПЛО —<br><i>ЭТО КОНТРОЛЬ.</i>',stoveRules:[['ДЫМОХОД','Очистите от сажи.'],['ТЯГА','Проверьте перед топкой.'],['ТРЕЩИНЫ','Устраните повреждения.'],['ОДЕЖДА','Не сушите вещи на печи.']],
fireSmall:'03 / ЕСЛИ НАЧАЛСЯ ПОЖАР',fireBtn:'СКАЧАТЬ ПАМЯТКУ PDF ↓',fireTitle:'НЕ ИЩИ<br><em>ВЕЩИ.</em><br>ИЩИ ВЫХОД.',fireP:'Как можно быстрее покиньте опасную зону. Не прячьтесь и не пользуйтесь лифтом.',fireSteps:[['Звони','101 / 112'],['Выходи','сразу'],['Не пользуйся','лифтом'],['Не возвращайся','за вещами']],
electricSmall:'04 / ЭЛЕКТРИКА',electricBtn:'СКАЧАТЬ ПАМЯТКУ PDF ↓',electricTitle:'УХОДИШЬ?<br><em>ВЫКЛЮЧИ.</em>',electric:[['ПОВРЕЖДЁННЫЕ ПРОВОДА — НЕТ','Не используйте кабели с повреждённой изоляцией.'],['ПЕРЕГРУЗКА — НЕТ','Не подключайте множество мощных приборов к одной розетке.'],['УХОДИШЬ — ПРОВЕРЬ','Утюг, плита и обогреватель должны быть выключены.'],['ДЕТИ — ПОД ПРИСМОТРОМ','Не оставляйте детей одних рядом с электроприборами.']],
alarmSmall:'05 / ИЗВЕЩАТЕЛЬ',alarmBtn:'СКАЧАТЬ ПАМЯТКУ PDF ↓',alarmTitle:'МАЛЕНЬКИЙ<br>ПРИБОР.<br><em>БОЛЬШАЯ<br>ЗАЩИТА.</em>',alarmP:'Дымовой извещатель помогает заметить пожар на ранней стадии и даёт время на эвакуацию.',alarmCheck:'ПРОВЕРИТЬ В СПИСКЕ →',alarmBadge:'ПРОВЕРЯЙ<br>РАБОТУ<br>РЕГУЛЯРНО',
checkSmall:'06 / 60 СЕКУНД',checkTitle:'ТВОЙ ДОМ<br><em>ПРОВЕРЕН?</em>',checkP:'Отметьте выполненные пункты. Прогресс сохраняется на этом устройстве.',reset:'СБРОСИТЬ ПРОВЕРКУ',checkItems:['Окна защищены блокираторами','Дети не остаются без присмотра','Дымоход очищен','Печь без повреждений','На печи нет вещей','Провода без повреждений','Розетки не перегружены','Дымовой извещатель работает','Батарея извещателя проверена','Все знают 101 и 112'],checkCount:'10 пунктов',
emergencySmall:'ЕСЛИ НУЖНА ПОМОЩЬ',emergencyP:'Назовите адрес, сообщите, что произошло, и следуйте инструкциям диспетчера.',calls:['ПОЖАРНАЯ','ЕДИНЫЙ НОМЕР'],
appSmall:'ДЕПАРТАМЕНТ ПО ЧС СКО · APP',appTitle:'ПАМЯТКА<br><em>ВСЕГДА С СОБОЙ.</em>',appP:'Установите памятку как приложение на телефон. Она открывается отдельным окном, запоминает вашу проверку дома и доступна даже без интернета после первого открытия.',install:'УСТАНОВИТЬ ПРИЛОЖЕНИЕ',hint:'Android / Chrome · iPhone / Safari',features:[['ОФЛАЙН','Основные памятки сохраняются на устройстве.'],['БЫСТРО','Открывается с иконки прямо с рабочего стола.'],['ТО ЖЕ СОДЕРЖАНИЕ','Разделы, проверка, PDF и QR остаются внутри.']],
botSmall:'TELEGRAM · ДЧС СКО',botTitle:'ЧАТ-БОТ<br><em>ДЧС СКО.</em>',botP:'Откройте официальный бот Департамента по чрезвычайным ситуациям Северо-Казахстанской области в Telegram.',botOfficial:'ОФИЦИАЛЬНЫЙ БОТ ДЧС СКО',botButton:'ОТКРЫТЬ ЧАТ-БОТ',qrSmall:'07 / ПАМЯТКА В ОДИН КЛИК',qrTitle:'СКАНИРУЙ.<br><em>СОХРАНЯЙ.</em><br>ПЕРЕДАВАЙ.',qrP:'QR-код ведёт прямо на эту страницу. Его удобно разместить на плакате, в подъезде или в школьном уголке безопасности.',copy:'СКОПИРОВАТЬ ССЫЛКУ',qrLabel:'QR / SAFETY · LIVE',qrB:'НАВЕДИТЕ КАМЕРУ',qrE:'Код обновляется под адрес страницы',footer:'ДЕПАРТАМЕНТ ПО ЧС СКО ПРЕДУПРЕЖДАЕТ',top:'↑ НАВЕРХ',mobile:['Главная','Разделы','Проверка','QR','Вызов'],gameSmall:'07 / МИНИ-ИГРА',gameTitle:'СПАСИ<br><em>ДОМ.</em>',gameP:'Найдите все опасности в комнате и устраните их. Выберите предметы, которые могут привести к пожару или травме.',gameStats:['ОЧКОВ','СЕКУНД','ОПАСНОСТЕЙ'],gameStart:'НАЧАТЬ ИГРУ',gameRoom:'Игровая комната',gameHazards:['Опасность: открытое окно','Опасность: плита','Опасность: перегруженная розетка','Опасность: свеча','Опасность: заблокированный выход'],gameMessage:'Нажмите «Начать игру»',installToastTitle:'Установить «ДЧС СКО»?',installToastText:'Памятка появится на экране телефона.',installToastButton:'УСТАНОВИТЬ',close:'Закрыть',themeLabels:['СВЕТЛАЯ','ТЁМНАЯ','КОНТРАСТ']},
kz:{
nav:['01 БАЛАЛАР','02 ПЕШ','03 ӨРТ','04 ЭЛЕКТР','05 ТЕКСЕРУ','BOT','APP'],
heroEy:'ЖАДНАМА · ОТБАСЫ · ҚАУІПСІЗДІК',heroTitle:'ҮЙ,<br><span>ҚАУІПСІЗ</span><br>БОЛСЫН.',heroP:'Қысқа интерактивті жаднама: терезелерді, пешті, электр құралдарын тексеріп, отбасыңызды төтенше жағдайға дайындаңыз.',check:'ҮЙДІ ТЕКСЕРУ',quick:'НЕГІЗГІСІНЕ ӨТУ',fire:'ӨРТ СӨНДІРУ<br>ҚЫЗМЕТІ',unified:'БІРЫҢҒАЙ<br>НОМЕР',brand:'СҚО ТЖ ДЕПАРТАМЕНТІ ЕСКЕРТЕДІ',
quickSmall:'НЕДЕН БАСТАУ КЕРЕК',quickTitle:'Бүгін<br><em>тексеру керек</em> 4 нәрсе.',quickCards:[['ТЕРЕЗЕ','Блокираторлар · жиһаз'],['ПЕШ','Мұржа · жарықтар · тарту'],['ЭЛЕКТР','Сымдар · розеткалар · құралдар'],['ХАБАРЛАҒЫШ','Жұмыс · батарея · сынақ']],
sitSmall:'ЖАҒДАЙДЫ ТАҢДАҢЫЗ',sitTitle:'СІЗДІ<br><em>НЕ МАЗАЛАЙДЫ?</em>',sitP:'Барлық жаднаманы парақтамаңыз. Қажетті жағдайды таңдаңыз — сайт сізді керек әрекеттерге бірден апарады.',sitCards:['Бала<br>терезе жанында','Пеш<br>және жылыту','Өрт<br>басталды','Электр<br>қауіпсіздігі','Өрт<br>хабарлағышы'],
downloadSmall:'САҚТАП АЛУҒА БОЛАДЫ',downloadTitle:'Жаднаманы қазақ тілінде жүктеп алыңыз',downloadLabels:['ТЕРЕЗЕ ↓','ПЕШ ↓','ӨРТ ↓','ЭЛЕКТР ↓','ХАБАРЛАҒЫШ ↓'],
manifestoSmall:'ЕҢ МАҢЫЗДЫСЫ',manifestoTitle:'Қауіп алдын ала<br>ескертпейді.',manifestoP:'Сондықтан үйді бірдеңе болғаннан <strong>бұрын</strong> тексерген дұрыс. Мұнда — артық сөзсіз нақты әрекеттер.',
kidsSmall:'01 / БАЛАЛАР',kidsBtn:'ЖАДНАМАНЫ PDF ЖҮКТЕУ ↓',kidsTitle:'Кішкентай<br><em>қадам.</em> Үлкен қорғаныс.',kidsCaption:'ТЕРЕЗЕ ≠ ОЙЫН АЛАҢЫ',kidsRulesTitle:'БЕС ӘДЕТ',kidsRules:['Баланы қараусыз қалдырмаңыз.','Терезені толық ашық қалдырмаңыз.','Терезелерге блокираторлар орнатыңыз.','Терезе маңына жиһаз қоймаңыз.','Балаға ашық терезенің қауіпті екенін түсіндіріңіз.'],
stoveSmall:'02 / ЖЫЛЫТУ',stoveBtn:'ЖАДНАМАНЫ PDF ЖҮКТЕУ ↓',stoveTitle:'СУЫҚ ТҮСПЕЙ ТҰРЫП<br><em>ПЕШТІ ТЕКСЕРІҢІЗ.</em>',stoveOverlay:'ЖЫЛУ —<br><i>БАҚЫЛАУДА.</i>',stoveRules:[['МҰРЖА','Күйеден тазалаңыз.'],['ТАРТУ','Пештің тартуын тексеріңіз.'],['ЖАРЫҚТАР','Ақауларды жөндеңіз.'],['КИІМ','Пештің үстіне киім кептірмеңіз.']],
fireSmall:'03 / ӨРТ БОЛҒАНДА',fireBtn:'ЖАДНАМАНЫ PDF ЖҮКТЕУ ↓',fireTitle:'ЗАТТЫ<br><em>ІЗДЕМЕ.</em><br>ШЫҒУ ЖОЛЫН ІЗДЕ.',fireP:'Қауіпті аймақтан мүмкіндігінше тез шығыңыз. Жасырынбаңыз және лифт қолданбаңыз.',fireSteps:[['Хабарлас','101 / 112'],['Шық','бірден'],['Лифтті','қолданба'],['Қайта','кірме']],
electricSmall:'04 / ЭЛЕКТР',electricBtn:'ЖАДНАМАНЫ PDF ЖҮКТЕУ ↓',electricTitle:'КЕТІП БАРСЫҢ?<br><em>ӨШІР.</em>',electric:[['ЗАҚЫМДАЛҒАН СЫМ — ЖОҚ','Оқшаулауы зақымдалған кабельдерді пайдаланбаңыз.'],['АРТЫҚ ЖҮКТЕМЕ — ЖОҚ','Бір розеткаға тым көп қуатты құрал қоспаңыз.'],['КЕТЕРДЕ — ТЕКСЕР','Үтік, плита және жылытқыштар өшірілуі керек.'],['БАЛАЛАР — БАҚЫЛАУДА','Электр құралдарының жанында балаларды қараусыз қалдырмаңыз.']],
alarmSmall:'05 / ХАБАРЛАҒЫШ',alarmBtn:'ЖАДНАМАНЫ PDF ЖҮКТЕУ ↓',alarmTitle:'КІШКЕНЕ<br>ҚҰРЫЛҒЫ.<br><em>ҮЛКЕН<br>ҚОРҒАНЫС.</em>',alarmP:'Өрт хабарлағышы түтінді ерте анықтап, эвакуацияға уақыт береді.',alarmCheck:'ТЕКСЕРУ ТІЗІМІНЕ ӨТУ →',alarmBadge:'ЖҰМЫСЫН<br>ҮНЕМІ<br>ТЕКСЕРІҢІЗ',
checkSmall:'06 / 60 СЕКУНД',checkTitle:'ҮЙІҢІЗ<br><em>ТЕКСЕРІЛДІ МЕ?</em>',checkP:'Орындалған тармақтарды белгілеңіз. Нәтиже осы құрылғыда сақталады.',reset:'ТЕКСЕРУДІ ТАЗАРТУ',checkItems:['Терезелер блокиратормен қорғалған','Балалар қараусыз қалмайды','Мұржа тазартылған','Пеште ақау жоқ','Пештің үстінде киім жоқ','Сымдар зақымдалмаған','Розеткалар артық жүктелмеген','Өрт хабарлағышы жұмыс істейді','Хабарлағыш батареясы тексерілген','Барлығы 101 және 112 нөмірлерін біледі'],checkCount:'10 тармақ',
emergencySmall:'КӨМЕК КЕРЕК БОЛСА',emergencyP:'Мекенжайды айтыңыз, не болғанын хабарлаңыз және диспетчердің нұсқауын орындаңыз.',calls:['ӨРТ СӨНДІРУ','БІРЫҢҒАЙ НӨМІР'],
appSmall:'СҚО ТЖ ДЕПАРТАМЕНТІ · APP',appTitle:'ЖАДНАМА<br><em>ӘРҚАШАН ЖАНЫҢЫЗДА.</em>',appP:'Жаднаманы телефонға қосымша ретінде орнатыңыз. Ол бөлек терезеде ашылады, тексеру нәтижесін сақтайды және алғашқы ашудан кейін интернетсіз де қолжетімді.',install:'ҚОСЫМШАНЫ ОРНАТУ',hint:'Android / Chrome · iPhone / Safari',features:[['ОФЛАЙН','Негізгі жаднамалар құрылғыда сақталады.'],['ЖЫЛДАМ','Белгішеден бірден ашылады.'],['БАРЛЫҒЫ ІШІНДЕ','Бөлімдер, тексеру, PDF және QR сақталады.']],
botSmall:'TELEGRAM · СҚО ТЖ ДЕПАРТАМЕНТІ',botTitle:'ЧАТ-БОТ<br><em>СҚО ТЖ.</em>',botP:'Солтүстік Қазақстан облысы Төтенше жағдайлар департаментінің Telegram желісіндегі ресми чат-ботын ашыңыз.',botOfficial:'СҚО ТЖ ДЕПАРТАМЕНТІНІҢ РЕСМИ БОТЫ',botButton:'ЧАТ-БОТТЫ АШУ',qrSmall:'07 / БІР БАСУМЕН ЖАДНАМА',qrTitle:'СКАНЕРЛЕ.<br><em>САҚТА.</em><br>БӨЛІС.',qrP:'QR-код осы бетке тікелей апарады. Оны плакатта, подъезде немесе мектептегі қауіпсіздік бұрышында орналастыруға болады.',copy:'СІЛТЕМЕНІ КӨШІРУ',qrLabel:'QR / SAFETY · LIVE',qrB:'КАМЕРАНЫ БАҒЫТТАҢЫЗ',qrE:'Код бет мекенжайына бейімделеді',footer:'СҚО ТЖ ДЕПАРТАМЕНТІ ЕСКЕРТЕДІ',top:'↑ ЖОҒАРЫ',mobile:['Басты бет','Бөлімдер','Тексеру','QR','Қоңырау'],gameSmall:'07 / МИНИ-ОЙЫН',gameTitle:'ҮЙДІ<br><em>ҚҰТҚАР.</em>',gameP:'Бөлмедегі барлық қауіпті жағдайды тауып, жойыңыз. Өртке немесе жарақатқа әкелуі мүмкін заттарды таңдаңыз.',gameStats:['ҰПАЙ','СЕКУНД','ҚАУІП'],gameStart:'ОЙЫНДЫ БАСТАУ',gameRoom:'Ойын бөлмесі',gameHazards:['Қауіп: ашық терезе','Қауіп: плита','Қауіп: артық жүктелген розетка','Қауіп: майшам','Қауіп: бұғатталған шығу жолы'],gameMessage:'«Ойынды бастау» түймесін басыңыз',installToastTitle:'«СҚО ТЖ» қосымшасын орнату?',installToastText:'Жаднама телефон экранында пайда болады.',installToastButton:'ОРНАТУ',close:'Жабу',themeLabels:['ЖАРЫҚ','ҚАРАҢҒЫ','КОНТРАСТ']}
};

const memoFiles={kids:{ru:'windows-ru.pdf',kz:'windows-kz.pdf'},stove:{ru:'stove-ru.pdf',kz:'stove-kz.pdf'},fire:{ru:'fire-ru.pdf',kz:'fire-kz.pdf'},electric:{ru:'electric-ru.pdf',kz:'electric-kz.pdf'},alarm:{ru:'alarm-ru.pdf',kz:'alarm-kz.pdf'}};
const memoImages={stove:{ru:'assets/stove-ru.jpg',kz:'assets/stove-kz.jpg'},alarm:{ru:'assets/alarm-ru.jpg',kz:'assets/alarm-kz.jpg'},fire:{ru:'assets/fire-rules.jpg',kz:'assets/fire-rules-2.jpg'}};

function setHTML(sel,v){const el=document.querySelector(sel); if(el) el.innerHTML=v;}
function setText(sel,v){const el=document.querySelector(sel); if(el) el.textContent=v;}
function setAttr(sel,a,v){const el=document.querySelector(sel); if(el) el.setAttribute(a,v);}
function applyLang(lang){
 const t=I18N[lang]; document.documentElement.lang=lang; localStorage.setItem('safeHomeLang',lang);
 document.querySelectorAll('.langBtn').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));
 document.querySelectorAll('nav a').forEach((a,i)=>a.textContent=t.nav[i]||'');
 setText('.eyebrow',t.heroEy); setHTML('.heroText h1',t.heroTitle); setText('.heroText p',t.heroP); setText('.actions .red',t.check+' ↓'); setText('.textlink',t.quick+' →');
 const labels=document.querySelectorAll('.nums label'); if(labels[0]) labels[0].innerHTML=t.fire; if(labels[1]) labels[1].innerHTML=t.unified;
 setText('.logo b',t.brand);
 setText('.quick>div>small',t.quickSmall); setHTML('.quick h2',t.quickTitle);
 document.querySelectorAll('.quickGrid a').forEach((a,i)=>{a.querySelector('strong').textContent=t.quickCards[i][0];a.querySelector('small').textContent=t.quickCards[i][1]});
 setText('.situationHead small',t.sitSmall); setHTML('.situationHead h2',t.sitTitle); setText('.situationHead p',t.sitP); document.querySelectorAll('.sCard strong').forEach((x,i)=>x.innerHTML=t.sitCards[i]);
 setText('.downloadStrip small',t.downloadSmall); setText('.downloadStrip strong',t.downloadTitle); document.querySelectorAll('.downloadLinks a').forEach((a,i)=>{a.textContent=t.downloadLabels[i]; const keys=['kids','stove','fire','electric','alarm']; a.href='downloads/'+memoFiles[keys[i]][lang];});
 setText('.manifesto small',t.manifestoSmall); setHTML('.manifesto h2',t.manifestoTitle); setHTML('.manifesto p',t.manifestoP);
 setText('#kids .heading small',t.kidsSmall); setText('#kids .downloadBtn',t.kidsBtn); setHTML('#kids .heading h2',t.kidsTitle); setText('#kids .photo span',t.kidsCaption); setText('#kids .rules>small',t.kidsRulesTitle); document.querySelectorAll('#kids .rules>div').forEach((x,i)=>x.lastChild.textContent=t.kidsRules[i]);
 setText('#stove .heading small',t.stoveSmall); setText('#stove .downloadBtn',t.stoveBtn); setHTML('#stove .heading h2',t.stoveTitle); setHTML('#stove .widePhoto strong',t.stoveOverlay); document.querySelectorAll('#stove .four article').forEach((x,i)=>{x.querySelector('h3').textContent=t.stoveRules[i][0];x.querySelector('p').textContent=t.stoveRules[i][1]});
 setText('#fire .fireText small',t.fireSmall); setText('#fire .fireBtn',t.fireBtn); setHTML('#fire .fireText h2',t.fireTitle); setText('#fire .fireText p',t.fireP); document.querySelectorAll('#fire .steps div').forEach((x,i)=>{x.childNodes[2].textContent=t.fireSteps[i][0]+' ';x.querySelector('strong').textContent=t.fireSteps[i][1]});
 setText('#electric .heading small',t.electricSmall); setText('#electric .downloadBtn',t.electricBtn); setHTML('#electric .heading h2',t.electricTitle); document.querySelectorAll('#electric .elist article').forEach((x,i)=>{x.querySelector('b').textContent=t.electric[i][0];x.querySelector('p').innerHTML='<b>'+t.electric[i][0]+'</b><br>'+t.electric[i][1]});
 setText('#alarm .alarm small',t.alarmSmall); setText('#alarm .downloadBtn',t.alarmBtn); setHTML('#alarm h2',t.alarmTitle); setText('#alarm p',t.alarmP); setText('#alarm .outline',t.alarmCheck); setHTML('#alarmPicBadge',t.alarmBadge);
 setText('#check .heading small',t.checkSmall); setHTML('#check .heading h2',t.checkTitle); setText('#check .heading p',t.checkP); setText('#reset',t.reset); setText('.meterNote span:last-child',t.checkCount);
 const boxes=document.querySelectorAll('.checklist label'); boxes.forEach((x,i)=>{x.lastChild.textContent=t.checkItems[i]});
 setText('.botCopy>small',t.botSmall); setHTML('.botCopy h2',t.botTitle); setText('.botCopy p',t.botP); setText('.botMeta b',t.botOfficial); setHTML('.botButton',t.botButton+' <span>↗</span>');
 setText('.emergency small',t.emergencySmall); setText('.emergency p',t.emergencyP); document.querySelectorAll('.calls a').forEach((a,i)=>{a.firstChild.textContent=t.calls[i]+' ';});
 setText('.appCopy small',t.appSmall); setHTML('.appCopy h2',t.appTitle); setText('.appCopy p',t.appP); setText('#installApp',t.install+' ↓'); setText('#installHint',t.hint); document.querySelectorAll('.appFeatures div').forEach((x,i)=>{x.querySelector('strong').textContent=t.features[i][0];x.querySelector('small').textContent=t.features[i][1]});
 setText('.qr>div>small',t.qrSmall); setHTML('.qr h2',t.qrTitle); setText('.qr p',t.qrP); setText('#copyUrl',t.copy); setText('.qrLabel',t.qrLabel); setText('.qrbox>b',t.qrB); setText('.qrbox>em',t.qrE); setText('footer b',t.footer); setText('footer a',t.top);
 document.querySelectorAll('.mobileNav span').forEach((x,i)=>x.textContent=t.mobile[i]);
 // Game/UI translation.
 setText('.gameIntro>div>small',t.gameSmall); setHTML('.gameIntro h2',t.gameTitle); setText('.gameIntro>p',t.gameP);
 document.querySelectorAll('.gameStats span').forEach((x,i)=>x.textContent=t.gameStats[i]);
 setHTML('#gameStart',t.gameStart+' <span>→</span>'); setAttr('#gameRoom','aria-label',t.gameRoom);
 document.querySelectorAll('.hotspot').forEach((x,i)=>x.setAttribute('aria-label',t.gameHazards[i]));
 setText('#gameMessage',t.gameMessage);
 setText('#installToast b',t.installToastTitle); setText('#installToast span',t.installToastText); setText('#toastInstall',t.installToastButton); setAttr('#toastClose','aria-label',t.close);
 document.documentElement.dataset.lang=lang;
 document.dispatchEvent(new CustomEvent('safeLangChanged',{detail:{lang:lang,translations:t}}));
 // Separate language images for the memo sections.
 if(memoImages.stove){document.querySelector('#stove .widePhoto img').src=memoImages.stove[lang]}
 if(memoImages.alarm){document.querySelector('#alarm .alarmPic img').src=memoImages.alarm[lang]}
 if(memoImages.fire){document.querySelector('#fire .firePic img').src=memoImages.fire[lang]}
 // Per-memo language-specific PDF buttons.
 Object.keys(memoFiles).forEach(id=>{const a=document.querySelector('#'+id+' .downloadBtn');if(a)a.href='downloads/'+memoFiles[id][lang]});
 document.querySelectorAll('[data-lang-label]').forEach(x=>x.textContent=lang.toUpperCase());
}

// Language switcher
const switcher=document.createElement('div'); switcher.className='langSwitch'; switcher.innerHTML='<button class="langBtn" data-lang="ru">RU</button><span>/</span><button class="langBtn" data-lang="kz">KZ</button>'; document.querySelector('.topActions').prepend(switcher);
switcher.querySelectorAll('.langBtn').forEach(b=>b.addEventListener('click',()=>applyLang(b.dataset.lang)));

const lang=localStorage.getItem('safeHomeLang')||'ru';
// Existing checklist labels are generated before this script runs.
applyLang(lang);
